# Generated by Django 5.2.17 on 2026-09-11 09:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_number', models.CharField(max_length=10)),
                ('coach_type', models.CharField(choices=[('1A', 'AC 1st Class (1A)'), ('2A', 'AC 2 Tier (2A)'), ('3A', 'AC 3 Tier (3A)'), ('3E', 'AC 3 Economy (3E)'), ('SL', 'Sleeper (SL)')], default='3A', max_length=20)),
            ],
            options={
                'ordering': ['train', 'coach_number'],
            },
        ),
        migrations.CreateModel(
            name='LinenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linen_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('qr_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('linen_type', models.CharField(choices=[('Bedsheet', 'Bedsheet'), ('Blanket', 'Blanket'), ('Towel', 'Towel'), ('Pillow Cover', 'Pillow Cover')], max_length=50)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('IN_LAUNDRY', 'In Laundry'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('LOADED_TO_TRAIN', 'Loaded to Train'), ('ASSIGNED', 'Assigned'), ('ISSUED', 'Issued'), ('COLLECTION_PENDING', 'Collection Pending'), ('RETURNED', 'Returned'), ('RECEIVED_AT_LAUNDRY', 'Received at Laundry'), ('WASHING', 'Washing'), ('READY_FOR_REISSUE', 'Ready for Reissue'), ('UNACCOUNTED', 'Unaccounted'), ('INVESTIGATION_REQUIRED', 'Investigation Required')], default='REGISTERED', max_length=30)),
                ('current_location', models.CharField(default='Central Railway Laundry', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=20, unique=True)),
                ('train_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['train_number'],
            },
        ),
        migrations.CreateModel(
            name='CollectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_quantity', models.IntegerField(default=0)),
                ('scanned_quantity', models.IntegerField(default=0)),
                ('missing_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DISCREPANCY', 'Discrepancy Detected')], default='IN_PROGRESS', max_length=20)),
                ('attender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_sessions', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_sessions', to='linen.coach')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_sessions', to='linen.train')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_qr', models.CharField(default='', max_length=100)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success - Verified & Returned'), ('ALREADY_RETURNED', 'Warning - Already Returned'), ('WRONG_COACH', 'Warning - Assigned to Different Coach'), ('WRONG_TRAIN', 'Warning - Assigned to Different Train'), ('NOT_ASSIGNED', 'Warning - Linen Not Assigned'), ('UNKNOWN_QR', 'Error - Unknown QR Code'), ('DUPLICATE_SCAN', 'Warning - Duplicate Scan in Current Session')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('collection_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='linen.collectionsession')),
                ('linen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='linen.linenitem')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='LinenLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REGISTERED', 'Registered in System'), ('LAUNDRY_RECEIVED', 'Laundry Received'), ('DISPATCHED', 'Dispatched from Laundry'), ('IN_TRANSIT', 'In Transit to Station'), ('TRAIN_LOADED', 'Loaded to Train'), ('COACH_ASSIGNED', 'Assigned to Coach'), ('BERTH_ASSIGNED', 'Assigned to Berth'), ('ISSUED_TO_PASSENGER', 'Issued to Passenger'), ('COLLECTION_STARTED', 'Collection Session Started'), ('RETURNED_BY_PASSENGER', 'Returned by Passenger'), ('COLLECTED_BY_ATTENDER', 'Collected by Attender'), ('HANDOVER_TO_LAUNDRY', 'Handover to Laundry'), ('RECEIVED_AT_LAUNDRY', 'Received at Laundry Station'), ('WASHING', 'In Washing Cycle'), ('READY_FOR_REISSUE', 'Ready for Reissue'), ('UNACCOUNTED', 'Item Unaccounted / Missing at Checkpoint'), ('INVESTIGATION_REQUIRED', 'Investigation Flagged')], max_length=40)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=200)),
                ('berth', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='linen.coach')),
                ('linen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='linen.linenitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='linen.train')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LinenAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berth', models.CharField(max_length=10)),
                ('passenger_reference', models.CharField(default='PNR-1001', max_length=50)),
                ('journey_date', models.DateField(default=django.utils.timezone.now)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_collection_time', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_status', models.CharField(choices=[('ACTIVE', 'Active / In Journey'), ('RETURNED', 'Returned'), ('UNACCOUNTED', 'Unaccounted')], default='ACTIVE', max_length=20)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='linen.coach')),
                ('linen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='linen.linenitem')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='linen.train')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddField(
            model_name='coach',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='linen.train'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ATTENDER', 'Train Attender'), ('LAUNDRY', 'Laundry Staff')], default='ADMIN', max_length=20)),
                ('badge_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('train', 'coach_number')},
        ),
    ]
