# Generated by Django 5.2.17 on 2026-09-12 04:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linenassignment',
            name='destination_station',
            field=models.CharField(default='Hyderabad (HYB)', max_length=100),
        ),
        migrations.AddField(
            model_name='linenassignment',
            name='source_station',
            field=models.CharField(default='New Delhi (NDLS)', max_length=100),
        ),
        migrations.CreateModel(
            name='PassengerPNR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('berth', models.CharField(max_length=10)),
                ('berth_type', models.CharField(default='Lower Berth', max_length=30)),
                ('source_station', models.CharField(default='New Delhi (NDLS)', max_length=100)),
                ('destination_station', models.CharField(default='Hyderabad (HYB)', max_length=100)),
                ('journey_date', models.DateField(default=django.utils.timezone.now)),
                ('departure_time', models.CharField(default='20:00', max_length=20)),
                ('expected_arrival_time', models.CharField(default='06:30', max_length=20)),
                ('passenger_label', models.CharField(default='Passenger 1 (Adult)', max_length=100)),
                ('status', models.CharField(default='CNF / Confirmed', max_length=30)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='linen.coach')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='linen.train')),
            ],
        ),
    ]
