# Generated by Django 5.2 on 2026-09-19 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linen', '0003_passengernr_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linenitem',
            name='settlement_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='linenitem',
            name='settlement_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CHARGED', 'Charged'), ('WAIVED', 'Waived')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='passengerpnr',
            name='boarding_status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Boarding now', 'Boarding now'), ('Not boarded', 'Not boarded')], default='Boarding now', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Supervisor (Admin)'), ('ATTENDANT', 'Attendant'), ('ATTENDER', 'Train Attendant'), ('LAUNDRY', 'Laundry Staff')], default='SUPERVISOR', max_length=20),
        ),
        migrations.CreateModel(
            name='CoachHandOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], default='Morning', max_length=20)),
                ('bedsheets_handed_over', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed')], default='CONFIRMED', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='linen.coach')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='linen.train')),
            ],
            options={
                'ordering': ['-date', 'train', 'coach'],
            },
        ),
    ]
