# Generated by Django 5.2 on 2026-09-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linen', '0004_linenitem_settlement_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zone',
            field=models.CharField(default='South Central Railway (SCR)', max_length=100),
        ),
    ]
